<?php

return [
    'privacy-policy' => [
        'title' => 'Privacy Policy',
        'sections' => [
            ['heading' => '1. Information We Collect', 'body' => 'We collect information you provide directly to us, such as your name, email address, company details, billing information, and the content of documents you create using Invoxaco. We also automatically collect technical information including IP address, browser type, device information, and usage data through cookies and similar technologies.'],
            ['heading' => '2. How We Use Your Information', 'body' => 'We use the information we collect to provide, maintain, and improve the Invoxaco service; to process payments and manage subscriptions; to send transactional emails (account verification, password resets, document delivery); to communicate product updates; and to detect and prevent fraud or abuse.'],
            ['heading' => '3. Document Data', 'body' => 'Documents you create are stored in your account and are only accessible to you, unless you explicitly enable a shareable link or email a document to a third party. We do not read, sell, or use the contents of your documents for advertising purposes.'],
            ['heading' => '4. Sharing of Information', 'body' => 'We do not sell your personal data. We may share information with service providers who help us operate Invoxaco (e.g. payment processors, email delivery providers, hosting providers), and when required to comply with law or protect our rights.'],
            ['heading' => '5. Data Retention', 'body' => 'We retain your account and document data for as long as your account is active. You may request deletion of your account and associated data at any time by contacting support@invoxaco.com.'],
            ['heading' => '6. Security', 'body' => 'We use industry-standard measures including encrypted connections (HTTPS), hashed passwords, and access controls to protect your data. No method of transmission or storage is 100% secure, but we work to protect your information.'],
            ['heading' => '7. Your Rights', 'body' => 'Depending on your jurisdiction, you may have the right to access, correct, export, or delete your personal data. See our GDPR and CCPA pages for region-specific rights and how to exercise them.'],
            ['heading' => '8. Changes to This Policy', 'body' => 'We may update this Privacy Policy from time to time. We will notify users of material changes via email or an in-app notice.'],
            ['heading' => '9. Contact Us', 'body' => 'Questions about this policy can be sent to support@invoxaco.com.'],
        ],
    ],
    'terms-of-service' => [
        'title' => 'Terms of Service',
        'sections' => [
            ['heading' => '1. Acceptance of Terms', 'body' => 'By creating an account or using Invoxaco, you agree to be bound by these Terms of Service. If you do not agree, do not use the service.'],
            ['heading' => '2. Description of Service', 'body' => 'Invoxaco is a web-based platform for generating, saving, editing, downloading, and emailing business documents such as invoices, contracts, and quotations.'],
            ['heading' => '3. Accounts', 'body' => 'You are responsible for maintaining the confidentiality of your account credentials and for all activity under your account. You must provide accurate registration information.'],
            ['heading' => '4. Subscription Plans &amp; Billing', 'body' => 'Invoxaco offers Free, Pro, and Premium subscription tiers. Paid plans are billed monthly or annually in advance and automatically renew unless cancelled. Fees are non-refundable except as described in our Refund Policy.'],
            ['heading' => '5. Acceptable Use', 'body' => 'You agree not to use Invoxaco to create fraudulent, illegal, or infringing documents, or to abuse, overload, or attempt unauthorized access to the service. See our Acceptable Use Policy for details.'],
            ['heading' => '6. Intellectual Property', 'body' => 'Invoxaco and its templates, software, and branding are owned by us. Documents you create using your own data remain yours.'],
            ['heading' => '7. Termination', 'body' => 'We may suspend or terminate accounts that violate these Terms. You may cancel your account at any time from your dashboard.'],
            ['heading' => '8. Disclaimer of Warranties', 'body' => 'Invoxaco is provided "as is" without warranties of any kind. Documents generated by the platform are templates and do not constitute legal advice; see our Disclaimer page.'],
            ['heading' => '9. Limitation of Liability', 'body' => 'To the maximum extent permitted by law, Invoxaco shall not be liable for indirect, incidental, or consequential damages arising from use of the service.'],
            ['heading' => '10. Changes to Terms', 'body' => 'We may update these Terms from time to time. Continued use of Invoxaco after changes constitutes acceptance of the revised Terms.'],
            ['heading' => '11. Contact', 'body' => 'Questions about these Terms can be sent to support@invoxaco.com.'],
        ],
    ],
    'refund-policy' => [
        'title' => 'Refund Policy',
        'sections' => [
            ['heading' => '1. Free Plan', 'body' => 'The Free plan has no charge and is not eligible for refunds.'],
            ['heading' => '2. Paid Subscriptions', 'body' => 'You may request a full refund within 7 days of your initial paid subscription purchase if you are not satisfied with Invoxaco. Refund requests after 7 days, or for renewal charges, are evaluated on a case-by-case basis.'],
            ['heading' => '3. How to Request a Refund', 'body' => 'Email support@invoxaco.com with your account email and the reason for your request. Approved refunds are returned to your original payment method within 5-10 business days.'],
            ['heading' => '4. Cancellations', 'body' => 'You can cancel your subscription at any time from your dashboard. Cancelling stops future renewals but does not automatically trigger a refund for the current billing period unless within the refund window above.'],
            ['heading' => '5. Downgrades', 'body' => 'If you downgrade from Pro/Premium to a lower tier, the change takes effect at the end of your current billing cycle; no partial refunds are issued for the unused portion of a cycle.'],
        ],
    ],
    'cookie-policy' => [
        'title' => 'Cookie Policy',
        'sections' => [
            ['heading' => '1. What Are Cookies', 'body' => 'Cookies are small text files stored on your device that help websites remember information about your visit.'],
            ['heading' => '2. How We Use Cookies', 'body' => 'Invoxaco uses essential cookies to keep you logged in and protect against CSRF attacks, and optional analytics cookies (e.g. Google Analytics, Microsoft Clarity) to understand how the service is used so we can improve it.'],
            ['heading' => '3. Third-Party Cookies', 'body' => 'Some cookies may be set by third-party analytics or advertising providers we use, such as Google Analytics or Meta Pixel, if enabled by the site administrator.'],
            ['heading' => '4. Managing Cookies', 'body' => 'Most browsers let you refuse or delete cookies. Disabling essential cookies may prevent you from logging in or using core features of Invoxaco.'],
            ['heading' => '5. Changes', 'body' => 'We may update this policy as our use of cookies evolves. Check back periodically for updates.'],
        ],
    ],
    'disclaimer' => [
        'title' => 'Disclaimer',
        'sections' => [
            ['heading' => '1. Not Legal or Financial Advice', 'body' => 'Documents generated by Invoxaco (including contracts, agreements, and financial documents) are general-purpose templates. They are not a substitute for advice from a qualified attorney, accountant, or tax professional. Use of these templates is at your own risk.'],
            ['heading' => '2. Accuracy', 'body' => 'While we strive to keep templates current and useful, we make no warranty that any document generated is suitable, compliant, or enforceable in your specific jurisdiction or circumstance.'],
            ['heading' => '3. Third-Party Links', 'body' => 'Our website may contain links to third-party sites. We are not responsible for the content or practices of those sites.'],
            ['heading' => '4. No Guarantee of Results', 'body' => 'Use of Invoxaco does not guarantee any particular business, legal, or financial outcome.'],
        ],
    ],
    'acceptable-use-policy' => [
        'title' => 'Acceptable Use Policy',
        'sections' => [
            ['heading' => '1. Prohibited Activities', 'body' => 'You may not use Invoxaco to: create fraudulent, forged, or deceptive documents intended to mislead a third party; generate content that is illegal, defamatory, or infringes the rights of others; attempt to gain unauthorized access to other accounts or our systems; or use automated tools to scrape or overload the service.'],
            ['heading' => '2. Account Sharing', 'body' => 'Accounts are for use by a single individual or organization. Team plans permit named team members under one billing account, subject to the plan\'s team member limit.'],
            ['heading' => '3. Enforcement', 'body' => 'Violation of this policy may result in suspension or termination of your account without refund.'],
            ['heading' => '4. Reporting Abuse', 'body' => 'If you become aware of misuse of Invoxaco, please report it to support@invoxaco.com.'],
        ],
    ],
    'data-processing-policy' => [
        'title' => 'Data Processing Policy',
        'sections' => [
            ['heading' => '1. Roles', 'body' => 'When you use Invoxaco to create documents containing personal data about your own clients or contacts, you act as the data controller for that data, and Invoxaco acts as a data processor on your behalf.'],
            ['heading' => '2. Processing Instructions', 'body' => 'We process personal data only as necessary to provide the service (storage, rendering, PDF/DOCX export, email delivery) and in accordance with your instructions as expressed through your use of the platform.'],
            ['heading' => '3. Sub-Processors', 'body' => 'We may engage sub-processors (such as hosting and email delivery providers) to support the service. We require sub-processors to provide an equivalent level of data protection.'],
            ['heading' => '4. Security Measures', 'body' => 'We maintain technical and organizational measures appropriate to the risk, including encrypted transport, access controls, and regular backups.'],
            ['heading' => '5. Data Subject Requests', 'body' => 'If you receive a request from one of your clients regarding their personal data stored in your Invoxaco documents, you are responsible for responding; we will provide reasonable assistance upon request to support@invoxaco.com.'],
        ],
    ],
    'gdpr-compliance' => [
        'title' => 'GDPR Compliance',
        'sections' => [
            ['heading' => '1. Overview', 'body' => 'If you are located in the European Economic Area (EEA), the General Data Protection Regulation (GDPR) gives you specific rights over your personal data, which Invoxaco respects.'],
            ['heading' => '2. Legal Basis for Processing', 'body' => 'We process personal data based on your consent, the necessity to perform our contract with you (providing the service), and our legitimate interests in operating and improving Invoxaco.'],
            ['heading' => '3. Your Rights', 'body' => 'You have the right to access, rectify, erase, restrict, or port your personal data, and to object to certain processing. You may exercise these rights by emailing support@invoxaco.com.'],
            ['heading' => '4. International Transfers', 'body' => 'Where personal data is transferred outside the EEA, we rely on appropriate safeguards such as Standard Contractual Clauses.'],
            ['heading' => '5. Data Protection Officer', 'body' => 'For GDPR-related inquiries, contact support@invoxaco.com.'],
        ],
    ],
    'ccpa-compliance' => [
        'title' => 'CCPA Compliance',
        'sections' => [
            ['heading' => '1. Overview', 'body' => 'If you are a California resident, the California Consumer Privacy Act (CCPA), as amended by the CPRA, gives you specific rights regarding your personal information.'],
            ['heading' => '2. Your Rights', 'body' => 'You have the right to know what personal information we collect, to request deletion of your personal information, to correct inaccurate information, and to opt out of the sale or sharing of personal information. Invoxaco does not sell your personal information.'],
            ['heading' => '3. Non-Discrimination', 'body' => 'We will not discriminate against you for exercising any of your CCPA rights.'],
            ['heading' => '4. How to Submit a Request', 'body' => 'You may submit a request to know, delete, or correct your information by emailing support@invoxaco.com from your registered account email address.'],
        ],
    ],
];
