<?php

return [
    'free' => [
        'name' => 'Free',
        'price_monthly' => 0,
        'price_yearly' => 0,
        'document_limit' => 10,
        'templates' => 'basic',
        'watermark' => true,
        'team_members' => 0,
        'custom_logo' => false,
        'docx_export' => false,
        'email_sending' => false,
        'client_management' => false,
        'white_label' => false,
        'api_access' => false,
        'ai_writer' => false,
        'priority_support' => false,
        'bulk_generation' => false,
    ],
    'pro' => [
        'name' => 'Pro',
        'price_monthly' => 9.99,
        'price_yearly' => 80,
        'document_limit' => 100,
        'templates' => 'premium',
        'watermark' => false,
        'team_members' => 0,
        'custom_logo' => true,
        'docx_export' => true,
        'email_sending' => true,
        'client_management' => true,
        'white_label' => false,
        'api_access' => false,
        'ai_writer' => false,
        'priority_support' => false,
        'bulk_generation' => false,
    ],
    'premium' => [
        'name' => 'Premium',
        'price_monthly' => 19.99,
        'price_yearly' => 160,
        'document_limit' => null, // unlimited
        'templates' => 'premium',
        'watermark' => false,
        'team_members' => null, // unlimited
        'custom_logo' => true,
        'docx_export' => true,
        'email_sending' => true,
        'client_management' => true,
        'white_label' => true,
        'api_access' => true,
        'ai_writer' => true,
        'priority_support' => true,
        'bulk_generation' => true,
    ],
];
