-- Extends the witness/governing-law field-quality pass from the core Legal
-- Documents category to every other "agreement"/"contract" generator across
-- HR, Construction, Real Estate, Freelancer, Business Operations, Marketing,
-- and Startup categories, so binding agreements outside the Legal Documents
-- category also read like properly executed contracts. Idempotent: each
-- statement only appends a field if one with that name doesn't already exist.

-- Already have governing_law: just add the witness line.
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','witness_name','label','Witness Name (optional)','type','text','required',false)) WHERE slug = 'employment-contract-generator' AND JSON_SEARCH(fields_schema, 'one', 'witness_name', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','witness_name','label','Witness Name (optional)','type','text','required',false)) WHERE slug = 'construction-contract-generator' AND JSON_SEARCH(fields_schema, 'one', 'witness_name', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','witness_name','label','Witness Name (optional)','type','text','required',false)) WHERE slug = 'freelance-contract-generator' AND JSON_SEARCH(fields_schema, 'one', 'witness_name', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','witness_name','label','Witness Name (optional)','type','text','required',false)) WHERE slug = 'independent-contractor-agreement-generator' AND JSON_SEARCH(fields_schema, 'one', 'witness_name', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','witness_name','label','Witness Name (optional)','type','text','required',false)) WHERE slug = 'vendor-agreement-generator' AND JSON_SEARCH(fields_schema, 'one', 'witness_name', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','witness_name','label','Witness Name (optional)','type','text','required',false)) WHERE slug = 'non-compete-agreement-generator' AND JSON_SEARCH(fields_schema, 'one', 'witness_name', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','witness_name','label','Witness Name (optional)','type','text','required',false)) WHERE slug = 'founders-agreement-generator' AND JSON_SEARCH(fields_schema, 'one', 'witness_name', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','witness_name','label','Witness Name (optional)','type','text','required',false)) WHERE slug = 'advisory-board-agreement-generator' AND JSON_SEARCH(fields_schema, 'one', 'witness_name', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','witness_name','label','Witness Name (optional)','type','text','required',false)) WHERE slug = 'sales-agreement-generator' AND JSON_SEARCH(fields_schema, 'one', 'witness_name', NULL, '$.fields[*].name') IS NULL;

-- Missing governing_law entirely: add it plus the witness line.
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','governing_law','label','Governing Law / Jurisdiction','type','text','required',false)) WHERE slug = 'subcontractor-agreement-generator' AND JSON_SEARCH(fields_schema, 'one', 'governing_law', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','witness_name','label','Witness Name (optional)','type','text','required',false)) WHERE slug = 'subcontractor-agreement-generator' AND JSON_SEARCH(fields_schema, 'one', 'witness_name', NULL, '$.fields[*].name') IS NULL;

UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','governing_law','label','Governing Law / Jurisdiction','type','text','required',false)) WHERE slug = 'rental-agreement-generator' AND JSON_SEARCH(fields_schema, 'one', 'governing_law', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','witness_name','label','Witness Name (optional)','type','text','required',false)) WHERE slug = 'rental-agreement-generator' AND JSON_SEARCH(fields_schema, 'one', 'witness_name', NULL, '$.fields[*].name') IS NULL;

UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','governing_law','label','Governing Law / Jurisdiction','type','text','required',false)) WHERE slug = 'real-estate-purchase-agreement-generator' AND JSON_SEARCH(fields_schema, 'one', 'governing_law', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','witness_name','label','Witness Name (optional)','type','text','required',false)) WHERE slug = 'real-estate-purchase-agreement-generator' AND JSON_SEARCH(fields_schema, 'one', 'witness_name', NULL, '$.fields[*].name') IS NULL;

UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','governing_law','label','Governing Law / Jurisdiction','type','text','required',false)) WHERE slug = 'property-management-agreement-generator' AND JSON_SEARCH(fields_schema, 'one', 'governing_law', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','witness_name','label','Witness Name (optional)','type','text','required',false)) WHERE slug = 'property-management-agreement-generator' AND JSON_SEARCH(fields_schema, 'one', 'witness_name', NULL, '$.fields[*].name') IS NULL;

UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','governing_law','label','Governing Law / Jurisdiction','type','text','required',false)) WHERE slug = 'retainer-agreement-generator' AND JSON_SEARCH(fields_schema, 'one', 'governing_law', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','witness_name','label','Witness Name (optional)','type','text','required',false)) WHERE slug = 'retainer-agreement-generator' AND JSON_SEARCH(fields_schema, 'one', 'witness_name', NULL, '$.fields[*].name') IS NULL;

UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','governing_law','label','Governing Law / Jurisdiction','type','text','required',false)) WHERE slug = 'influencer-agreement-generator' AND JSON_SEARCH(fields_schema, 'one', 'governing_law', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','witness_name','label','Witness Name (optional)','type','text','required',false)) WHERE slug = 'influencer-agreement-generator' AND JSON_SEARCH(fields_schema, 'one', 'witness_name', NULL, '$.fields[*].name') IS NULL;

UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','governing_law','label','Governing Law / Jurisdiction','type','text','required',false)) WHERE slug = 'advertising-agreement-generator' AND JSON_SEARCH(fields_schema, 'one', 'governing_law', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','witness_name','label','Witness Name (optional)','type','text','required',false)) WHERE slug = 'advertising-agreement-generator' AND JSON_SEARCH(fields_schema, 'one', 'witness_name', NULL, '$.fields[*].name') IS NULL;

UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','governing_law','label','Governing Law / Jurisdiction','type','text','required',false)) WHERE slug = 'equity-vesting-agreement-generator' AND JSON_SEARCH(fields_schema, 'one', 'governing_law', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','witness_name','label','Witness Name (optional)','type','text','required',false)) WHERE slug = 'equity-vesting-agreement-generator' AND JSON_SEARCH(fields_schema, 'one', 'witness_name', NULL, '$.fields[*].name') IS NULL;
