-- Adds a Terms/Notes field to generators that were missing one, so every
-- generator gets a Terms tab in the editor. Idempotent: each statement only
-- appends the field if a field with that name doesn't already exist.

UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','additional_terms','label','Additional Terms & Conditions','type','textarea','required',false)) WHERE slug = 'non-disclosure-agreement-generator' AND JSON_SEARCH(fields_schema, 'one', 'additional_terms', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','additional_terms','label','Additional Terms & Conditions','type','textarea','required',false)) WHERE slug = 'partnership-agreement-generator' AND JSON_SEARCH(fields_schema, 'one', 'additional_terms', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','additional_terms','label','Additional Terms & Conditions','type','textarea','required',false)) WHERE slug = 'power-of-attorney-generator' AND JSON_SEARCH(fields_schema, 'one', 'additional_terms', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','additional_terms','label','Additional Terms & Conditions','type','textarea','required',false)) WHERE slug = 'cease-and-desist-letter-generator' AND JSON_SEARCH(fields_schema, 'one', 'additional_terms', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','additional_terms','label','Additional Terms & Conditions','type','textarea','required',false)) WHERE slug = 'demand-letter-generator' AND JSON_SEARCH(fields_schema, 'one', 'additional_terms', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','additional_terms','label','Additional Terms & Conditions','type','textarea','required',false)) WHERE slug = 'termination-letter-generator' AND JSON_SEARCH(fields_schema, 'one', 'additional_terms', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','additional_terms','label','Additional Terms & Conditions','type','textarea','required',false)) WHERE slug = 'employee-warning-letter-generator' AND JSON_SEARCH(fields_schema, 'one', 'additional_terms', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','additional_terms','label','Additional Terms & Conditions','type','textarea','required',false)) WHERE slug = 'non-compete-agreement-generator' AND JSON_SEARCH(fields_schema, 'one', 'additional_terms', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','additional_terms','label','Additional Terms & Conditions','type','textarea','required',false)) WHERE slug = 'retainer-agreement-generator' AND JSON_SEARCH(fields_schema, 'one', 'additional_terms', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','additional_terms','label','Additional Terms & Conditions','type','textarea','required',false)) WHERE slug = 'property-management-agreement-generator' AND JSON_SEARCH(fields_schema, 'one', 'additional_terms', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','additional_terms','label','Additional Terms & Conditions','type','textarea','required',false)) WHERE slug = 'equity-vesting-agreement-generator' AND JSON_SEARCH(fields_schema, 'one', 'additional_terms', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','additional_terms','label','Additional Terms & Conditions','type','textarea','required',false)) WHERE slug = 'advisory-board-agreement-generator' AND JSON_SEARCH(fields_schema, 'one', 'additional_terms', NULL, '$.fields[*].name') IS NULL;

UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','notes','label','Additional Notes','type','textarea','required',false)) WHERE slug = 'affidavit-generator' AND JSON_SEARCH(fields_schema, 'one', 'notes', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','notes','label','Additional Notes','type','textarea','required',false)) WHERE slug = 'release-of-liability-generator' AND JSON_SEARCH(fields_schema, 'one', 'notes', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','notes','label','Additional Notes','type','textarea','required',false)) WHERE slug = 'resignation-letter-generator' AND JSON_SEARCH(fields_schema, 'one', 'notes', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','notes','label','Additional Notes','type','textarea','required',false)) WHERE slug = 'performance-review-form-generator' AND JSON_SEARCH(fields_schema, 'one', 'notes', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','notes','label','Additional Notes','type','textarea','required',false)) WHERE slug = 'change-order-generator' AND JSON_SEARCH(fields_schema, 'one', 'notes', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','notes','label','Additional Notes','type','textarea','required',false)) WHERE slug = 'punch-list-generator' AND JSON_SEARCH(fields_schema, 'one', 'notes', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','notes','label','Additional Notes','type','textarea','required',false)) WHERE slug = 'property-listing-sheet-generator' AND JSON_SEARCH(fields_schema, 'one', 'notes', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','notes','label','Additional Notes','type','textarea','required',false)) WHERE slug = 'eviction-notice-generator' AND JSON_SEARCH(fields_schema, 'one', 'notes', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','notes','label','Additional Notes','type','textarea','required',false)) WHERE slug = 'rent-receipt-generator' AND JSON_SEARCH(fields_schema, 'one', 'notes', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','notes','label','Additional Notes','type','textarea','required',false)) WHERE slug = 'business-proposal-generator' AND JSON_SEARCH(fields_schema, 'one', 'notes', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','notes','label','Additional Notes','type','textarea','required',false)) WHERE slug = 'project-brief-generator' AND JSON_SEARCH(fields_schema, 'one', 'notes', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','notes','label','Additional Notes','type','textarea','required',false)) WHERE slug = 'standard-operating-procedure-generator' AND JSON_SEARCH(fields_schema, 'one', 'notes', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','notes','label','Additional Notes','type','textarea','required',false)) WHERE slug = 'business-plan-generator' AND JSON_SEARCH(fields_schema, 'one', 'notes', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','notes','label','Additional Notes','type','textarea','required',false)) WHERE slug = 'memo-generator' AND JSON_SEARCH(fields_schema, 'one', 'notes', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','notes','label','Additional Notes','type','textarea','required',false)) WHERE slug = 'marketing-plan-generator' AND JSON_SEARCH(fields_schema, 'one', 'notes', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','notes','label','Additional Notes','type','textarea','required',false)) WHERE slug = 'sponsorship-proposal-generator' AND JSON_SEARCH(fields_schema, 'one', 'notes', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','notes','label','Additional Notes','type','textarea','required',false)) WHERE slug = 'event-marketing-plan-generator' AND JSON_SEARCH(fields_schema, 'one', 'notes', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','notes','label','Additional Notes','type','textarea','required',false)) WHERE slug = 'pitch-deck-outline-generator' AND JSON_SEARCH(fields_schema, 'one', 'notes', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','notes','label','Additional Notes','type','textarea','required',false)) WHERE slug = 'business-model-canvas-generator' AND JSON_SEARCH(fields_schema, 'one', 'notes', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','notes','label','Additional Notes','type','textarea','required',false)) WHERE slug = 'cap-table-generator' AND JSON_SEARCH(fields_schema, 'one', 'notes', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','notes','label','Additional Notes','type','textarea','required',false)) WHERE slug = 'executive-summary-generator' AND JSON_SEARCH(fields_schema, 'one', 'notes', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','notes','label','Additional Notes','type','textarea','required',false)) WHERE slug = 'cv-resume-generator' AND JSON_SEARCH(fields_schema, 'one', 'notes', NULL, '$.fields[*].name') IS NULL;
UPDATE document_templates SET fields_schema = JSON_ARRAY_APPEND(fields_schema, '$.fields', JSON_OBJECT('name','notes','label','Additional Notes','type','textarea','required',false)) WHERE slug = 'company-profile-generator' AND JSON_SEARCH(fields_schema, 'one', 'notes', NULL, '$.fields[*].name') IS NULL;
